### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/pw2-e1-irma-m#1]
Borraste al parecer sin querer toda la sección `head` junto con las etiquetas `meta` y `title`, además, el encabezado `h1` debe estar dentro de `body`

https://github.com/UniversidadCristobalColon/pw2-e1-irma-m/blob/d221daddb2e1d071764694151ec85899e7a4d773/pw2-e1.html#L4

**Comment by irma-m** [comment]
[pw2-e1-irma-m-master.zip](https://github.com/UniversidadCristobalColon/pw2-e1-irma-m/files/3665138/pw2-e1-irma-m-master.zip)
